// Middlegame lessons (tier 9).
// Generated by tools/build-content.js — edit the data in tools/, then rebuild.
(function(){var C=window.KS_CONTENT=window.KS_CONTENT||{tiers:[],lessons:[],puzzles:[]};
C.lessons=C.lessons.concat(
[
 {
  "id": "m-plan",
  "tier": 9,
  "title": "How to actually make a plan",
  "body": "A plan is not 'attack the king'. It is a small, concrete improvement you can name: put the knight on d5, double on the c-file, trade the good bishop, win the d6 pawn. Find the worst-placed piece you own and the weakest square they own, and connect the two. That is a plan.",
  "points": [
   "Name the target square or pawn out loud",
   "Improve your worst piece — always a good plan",
   "Small plans in sequence beat one grand plan"
  ],
  "mode": "read"
 },
 {
  "id": "m-evaluate",
  "tier": 9,
  "title": "Evaluating a position in five questions",
  "body": "Before choosing a move, judge where you stand. Material, king safety, pawn structure, piece activity, and space. Whichever of those you are winning is the one to play towards; whichever you are losing is the one to fix or to avoid opening up. Most bad moves come from playing against the wrong feature.",
  "points": [
   "Material — king safety — structure — activity — space",
   "Play towards your advantage, not away from it",
   "If you are worse in one area, do not open the position there"
  ],
  "mode": "read"
 },
 {
  "id": "m-worstpiece",
  "tier": 9,
  "title": "Improve your worst piece",
  "body": "When you cannot find anything, look for the piece doing the least and give it a job. This one habit turns aimless moves into progress and is the closest thing to a universal rule in the middlegame. Strong players do it constantly; weak players shuffle their already-good pieces.",
  "points": [
   "Find the piece with the fewest useful squares",
   "Give it a route, even if it takes three moves",
   "Never move a good piece when a bad one needs help"
  ],
  "mode": "read"
 },
 {
  "id": "m-iqp",
  "tier": 9,
  "title": "The isolated queen's pawn",
  "body": "An isolated pawn is dynamic in the middlegame and weak in the endgame. The owner gets open files either side, an outpost on the square in front's neighbours, and attacking chances; the defender must blockade the pawn with a knight, trade pieces and head for the endgame. Both plans are correct — for their side.",
  "points": [
   "Attacker: keep pieces on, use e5/c5 outposts, attack",
   "Defender: blockade on d5, trade pieces, reach the endgame",
   "The pawn is strong while it is dynamic and weak once it is still"
  ],
  "mode": "explore",
  "note": "White's d4 pawn is isolated. White wants pieces on and an attack; Black wants trades.",
  "fen": "rnbqk2r/pp2bppp/4p3/3n4/3P4/2N2N2/PP3PPP/R1BQKB1R w KQkq - 0 8"
 },
 {
  "id": "m-blockade",
  "tier": 9,
  "title": "The blockade",
  "body": "A passed or isolated pawn is only dangerous when it moves. Park a piece directly in front of it — ideally a knight, which loses nothing by standing still — and the pawn is neutralised and becomes a permanent weakness instead. Nimzowitsch called it restrain, blockade, destroy.",
  "points": [
   "A knight is the ideal blockader — it still controls squares",
   "Blockade first, win the pawn later",
   "Restrain, blockade, then destroy"
  ],
  "fen": "r2q1rk1/pp3ppp/4pn2/3n4/3P4/2N1BN2/PP3PPP/R2Q1RK1 w - - 0 1",
  "mode": "explore",
  "note": "The knight on d5 sits in front of the isolated d4 pawn and cannot be driven away easily."
 },
 {
  "id": "m-hanging",
  "tier": 9,
  "title": "Hanging pawns",
  "body": "Two connected pawns on half-open files with no friendly pawns beside them, usually on c and d. They control valuable squares and can advance to open lines, but if they are forced to move they become weak. The defender's plan is to make one of them advance, then attack the square it left.",
  "points": [
   "Strong while they stand side by side",
   "Force one to advance and the other becomes weak",
   "Owner: look for the right moment to push and open lines"
  ],
  "fen": "r2q1rk1/pp2bppp/4pn2/8/2PP4/2N1PN2/P4PPP/R2Q1RK1 w - - 0 1",
  "mode": "explore",
  "note": "The c4 and d4 pawns are hanging. They look imposing, but each needs the other to stay put."
 },
 {
  "id": "m-backward",
  "tier": 9,
  "title": "Backward pawns and the squares in front",
  "body": "A backward pawn cannot be defended by another pawn and sits on a half-open file. The pawn itself is a target, but the real prize is the hole directly in front of it, which no pawn can ever attack. Plant a knight there and the game often plays itself.",
  "points": [
   "Attack it down the half-open file with rooks",
   "Occupy the hole in front of it with a knight",
   "Do not let it advance and free itself"
  ],
  "fen": "r2q1rk1/pp1n1ppp/2pb1n2/3p4/3P4/2NBPN2/PP3PPP/R2Q1RK1 w - - 0 1",
  "mode": "explore",
  "note": "Black's c6 pawn is backward on the half-open c-file, and c5 is a permanent hole."
 },
 {
  "id": "m-space",
  "tier": 9,
  "title": "Using a space advantage",
  "body": "Space is only an advantage if you keep enough pieces to use it. The cramped side wants trades, because every trade gives his remaining pieces more room. So the rule is simple and often forgotten: when you have more space, avoid trades and manoeuvre; when you are cramped, trade whenever you can.",
  "points": [
   "More space: avoid trades, keep pieces on",
   "Cramped: trade pieces at every opportunity",
   "Space without pieces is just a weakness waiting to happen"
  ],
  "mode": "read"
 },
 {
  "id": "m-openfile",
  "tier": 9,
  "title": "Winning an open file",
  "body": "Open files belong to whoever doubles first. But occupying a file is only the means — the end is a way in: an entry square on the seventh or eighth rank. If there is no entry square, the file is decoration. Look for the invasion point before you commit both rooks.",
  "points": [
   "Double rooks before invading, never after",
   "Find the entry square first — no entry, no advantage",
   "Contest the file or lose it completely"
  ],
  "fen": "3r1rk1/pp3ppp/2p5/8/8/2P5/PP3PPP/3R1RK1 w - - 0 1",
  "mode": "explore",
  "note": "The d-file is open and contested. Whoever doubles first and finds an entry square owns it."
 },
 {
  "id": "m-rooklift",
  "tier": 9,
  "title": "The rook lift",
  "body": "Rooks do not have to wait for open files. Lifting one to the third or fourth rank and swinging it across is one of the fastest ways to add an attacker to a kingside assault, and it is the standard follow-up to a pawn storm that has run out of pawns.",
  "points": [
   "Re1-e3-g3 or Ra1-a3-h3 brings a rook in fast",
   "Works especially well when the centre is closed",
   "One extra attacker often decides the attack"
  ],
  "fen": "r1bq1rk1/pp3ppp/2n1pn2/2pp4/3P4/2PBPN2/PP3PPP/RNBQR1K1 w - - 0 1",
  "mode": "explore",
  "note": "Re1-e3 and then across to g3 or h3 adds a heavy piece to the kingside in two moves."
 },
 {
  "id": "m-bishoppair",
  "tier": 9,
  "title": "The bishop pair",
  "body": "Two bishops cover both colours between them, which is why the pair is worth roughly half a pawn. The way to use them is to open the position: trade pawns, create long diagonals, and avoid closing lines. The way to fight them is the opposite — keep the structure locked and trade one off.",
  "points": [
   "Open the position to make the pair count",
   "The side without them wants a closed, blocked structure",
   "Trading one bishop off is a real achievement for the defender"
  ],
  "mode": "read"
 },
 {
  "id": "m-colourcomplex",
  "tier": 9,
  "title": "Weak colour complexes",
  "body": "When several pawns sit on one colour, every square of the other colour around them is permanently weak. Lose the bishop that covers those squares and the weakness becomes fatal. This is why trading a fianchettoed bishop in front of your own king is so often the losing decision.",
  "points": [
   "Pawns on one colour weaken all squares of the other",
   "Never trade the bishop defending your weak colour",
   "Aim your pieces at the whole complex, not one square"
  ],
  "fen": "r1bq1rk1/pp2ppbp/2np2p1/8/3NP3/2N1B3/PPP2PPP/R2QKB1R w KQ - 0 1",
  "mode": "explore",
  "note": "Black's pawns are on dark squares around a fianchetto. Trading the g7 bishop would be serious."
 },
 {
  "id": "m-outpost2",
  "tier": 9,
  "title": "Building an outpost",
  "body": "An outpost is a square in enemy territory that no enemy pawn can ever attack. A knight there is worth more than a rook in many positions. Outposts are created, not found: provoke a pawn move, or trade the pawn that guards the square, and then bring the knight in a long, patient route.",
  "points": [
   "Provoke or trade to create the hole first",
   "Then bring the knight in — three moves is fine",
   "Support it with a pawn so it can never be evicted"
  ],
  "fen": "r1bq1rk1/pp3ppp/2n1pn2/3p4/3P4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 1",
  "mode": "explore",
  "note": "Manoeuvre a knight to e5 and support it with f4. Then it can never be driven away."
 },
 {
  "id": "m-greekgift",
  "tier": 9,
  "title": "The Greek gift sacrifice",
  "body": "Bxh7+ is the most common sacrifice in chess. It needs four things: a bishop on the b1-h7 diagonal, a knight ready to jump to g5, a queen that can reach h5, and no black knight on f6 to defend. Check all four before you play it — and check them before you allow it.",
  "points": [
   "Bishop, knight, queen access, and no ...Nf6 defender",
   "Bxh7+ Kxh7 Ng5+ Qh5 is the standard sequence",
   "Look for it every time your opponent has no knight on f6"
  ],
  "mode": "explore",
  "note": "Count the four conditions here. The f6 knight is the defender — that is why it had to go.",
  "fen": "r1bq1rk1/ppp1bppp/4pn2/8/3P4/3B1N2/PPP2PPP/R1BQK2R w KQ - 0 9"
 },
 {
  "id": "m-fianchetto-attack",
  "tier": 9,
  "title": "Attacking a fianchetto",
  "body": "Against a kingside fianchetto, the standard recipe is h4-h5 to open the h-file and the trade of the dark-squared bishop with Bh6 or Qd2 and Bh6. Once that bishop is gone the dark squares around the king cannot be defended and the heavy pieces walk in.",
  "points": [
   "h4-h5 to open the h-file",
   "Trade the g7 bishop with Bh6 — that is the key piece",
   "Then bring the queen and rooks to the dark squares"
  ],
  "fen": "r1bq1rk1/ppp1ppbp/2np1np1/8/3PP3/2N1BP2/PPPQ2PP/R3KBNR w KQ - 0 1",
  "mode": "explore",
  "note": "Qd2 and Be3 are already set for Bh6. Add h4-h5 and the attack plays itself."
 },
 {
  "id": "m-oppositecastle",
  "tier": 9,
  "title": "Opposite-side castling",
  "body": "When kings go to opposite wings, the game becomes a pure race and normal rules stop applying. Pawns in front of your own king are attackers, not defenders, so push them. Do not waste a single move: the player who is one tempo faster usually mates first, whatever the material count says.",
  "points": [
   "Push the pawns in front of your own king — they are attackers",
   "Do not defend passively; count the race instead",
   "One tempo is worth more than one pawn here"
  ],
  "fen": "2kr1b1r/ppp1pppp/2n2n2/8/3P4/2N1B3/PPP1BPPP/2KR2NR w - - 0 1",
  "mode": "explore",
  "note": "Both kings are on the queenside here, so the attack must come in the centre or with pawns."
 },
 {
  "id": "m-pawnstorm",
  "tier": 9,
  "title": "Pawn storms",
  "body": "A pawn storm needs a closed or locked centre. If the centre can be opened, your advancing pawns are just weaknesses and the counter-blow in the middle arrives before your attack does. Lock the centre first, then storm — in that order, every time.",
  "points": [
   "Never storm a wing while the centre is open",
   "Lock the centre, then push the pawns",
   "Open one file, then bring the heavy pieces"
  ],
  "fen": "r1bq1rk1/ppp2ppp/2np1n2/3Pp3/2P1P3/2N2N2/PP3PPP/R1BQ1RK1 w - - 0 1",
  "mode": "explore",
  "note": "The centre is locked by d5 and e5. That is exactly when a kingside or queenside storm works."
 },
 {
  "id": "m-exchangesac",
  "tier": 9,
  "title": "The exchange sacrifice",
  "body": "Giving a rook for a minor piece is sound far more often than club players believe. The compensation is usually a permanent structural gain: a destroyed pawn shield, a monster knight that can never be evicted, or control of a colour complex. Petrosian built a career on it.",
  "points": [
   "Rook for a knight or bishop, for a lasting positional gain",
   "Classic targets: Rxc3 wrecking the queenside, Rxf6 killing a defender",
   "Judge it by what is permanent, not what is immediate"
  ],
  "fen": "2r1r1k1/pp1b1ppp/1qnp1n2/8/3NP3/1BN1B3/PPP2PPP/2RQ1RK1 w - - 0 1",
  "mode": "explore",
  "note": "Ideas like Rxc6 trading a rook for the knight can be strong when it wrecks the structure."
 },
 {
  "id": "m-defence",
  "tier": 9,
  "title": "How to defend",
  "body": "Defence is a skill, not a punishment. Find the opponent's idea before you move, remove his best attacking piece by trading it, and look for the moment to give material back to kill the attack. A calm defender beats a wild attacker more often than the other way round.",
  "points": [
   "Name their threat before you choose a move",
   "Trade off the key attacking piece",
   "Returning material to blunt an attack is usually right"
  ],
  "mode": "read"
 },
 {
  "id": "m-counterattack",
  "tier": 9,
  "title": "Counter-attack in the centre",
  "body": "The classical answer to a wing attack is a break in the centre. Opening the middle while their pieces are committed to a flank punishes them for every move they spent on the wing. Look for ...d5 or ...e5 the moment your opponent starts pushing pawns at your king.",
  "points": [
   "A wing attack is answered in the centre",
   "Their attacking pieces are far from the middle",
   "Break with ...d5 or ...e5 as soon as it is playable"
  ],
  "fen": "r1bq1rk1/pp2bppp/2n1pn2/3p4/3P4/2N1PN2/PP2BPPP/R1BQ1RK1 w - - 0 1",
  "mode": "explore",
  "note": "If White ever storms the kingside, Black's answer is a central break, not a defensive shuffle"
 },
 {
  "id": "m-tempo",
  "tier": 9,
  "title": "Tempo and the initiative",
  "body": "Every move that forces a reply is a move your opponent does not get to use for his own plan. A string of forcing moves is called the initiative, and it is a real advantage even with equal material. Once you have it, keep making moves they must answer — the moment you play quietly, it is gone.",
  "points": [
   "Forcing them to react is itself an advantage",
   "Do not cash the initiative in for one pawn too early",
   "When you lose the initiative, switch to solid moves at once"
  ],
  "mode": "read"
 },
 {
  "id": "m-trades2",
  "tier": 9,
  "title": "The six rules of trading",
  "body": "Trades are the most frequent decisions you make and the most frequently made badly. Ahead in material, trade pieces. Cramped, trade pieces. Under attack, trade attackers. With more space, keep pieces on. Trade your bad piece for their good one, never the reverse.",
  "points": [
   "Ahead in material or cramped — trade",
   "More space or attacking — keep pieces on",
   "Always trade your worst piece for their best"
  ],
  "mode": "read"
 },
 {
  "id": "m-calculation",
  "tier": 9,
  "title": "How to calculate",
  "body": "List your candidate moves before you calculate any of them, or you will go deep down the first line you saw and miss the best. Then for each candidate, look at forcing moves only: checks, captures and threats, for both sides. Calculate to a quiet position, then judge it — do not stop in the middle of a sequence.",
  "points": [
   "List candidates first, then calculate",
   "Checks, captures, threats — for both sides",
   "Stop only at a quiet position, then evaluate"
  ],
  "mode": "read"
 },
 {
  "id": "m-blunder2",
  "tier": 9,
  "title": "A blunder check that works",
  "body": "Before every move, do three things. Say what your move leaves undefended. Look at every check your opponent has in reply. Look at every capture. It takes ten seconds and will save you more rating points than any opening you could learn in a month.",
  "points": [
   "What does my move leave hanging?",
   "What checks do they have now?",
   "What captures do they have now?"
  ],
  "mode": "read"
 },
 {
  "id": "m-quiet",
  "tier": 9,
  "title": "The quiet move",
  "body": "The hardest moves to find are the ones that do not check or capture. At the end of a forcing sequence, a calm move that simply adds a threat or removes an escape square is often what makes the whole combination work. When your calculation comes up one move short, look for the quiet one.",
  "points": [
   "Look for quiet moves at the end of a forcing line",
   "Removing a flight square is often the point",
   "If the combination 'nearly works', a quiet move usually fixes it"
  ],
  "fen": "6k1/5ppp/8/8/8/7Q/5PPP/6K1 w - - 0 1",
  "mode": "explore",
  "note": "There is no check that wins here. Progress comes from a quiet improving move instead."
 },
 {
  "id": "m-twoweak",
  "tier": 9,
  "title": "The principle of two weaknesses",
  "body": "One weakness is usually defensible: the opponent piles everything on it and holds. Create a second one on the other side of the board and his pieces cannot cover both. Almost every winning technique at master level is this idea — stretch the defence until it tears.",
  "points": [
   "One weakness can be defended; two usually cannot",
   "Open a second front on the opposite wing",
   "Make them choose which one to abandon"
  ],
  "mode": "read"
 },
 {
  "id": "m-restrict",
  "tier": 9,
  "title": "Restriction and domination",
  "body": "Before you attack a piece, take its squares away. A knight with no outposts and a bishop with no open diagonal are already half-lost. Restricting the enemy's pieces is slower than attacking them but far more permanent, and it is the essence of positional play.",
  "points": [
   "Take the squares before you take the piece",
   "A piece with no squares is already out of the game",
   "Fix enemy pawns on the colour of their own bishop"
  ],
  "fen": "6k1/5ppp/8/4n3/2P1P3/3P4/5PPP/6K1 w - - 0 1",
  "mode": "explore",
  "note": "Pawns on c4, d3 and e4 take almost every square from the black knight."
 },
 {
  "id": "m-whenattack",
  "tier": 9,
  "title": "When are you allowed to attack?",
  "body": "You may attack when you have more pieces pointing at their king than they have defending it, and when the centre is stable. If either is missing, the attack fails and you are left with the weaknesses you created. Count attackers and defenders before you commit a single pawn.",
  "points": [
   "Count attackers against defenders honestly",
   "The centre must be closed or firmly yours",
   "No advantage yet? Improve pieces instead"
  ],
  "mode": "read"
 },
 {
  "id": "m-sacseval",
  "tier": 9,
  "title": "Judging a sacrifice",
  "body": "If you can calculate it to mate or to material back, it is real — play it. If you cannot, ask what you get permanently: an exposed king, a destroyed structure, an unopposed piece. Permanent compensation is worth a pawn; a vague feeling is not.",
  "points": [
   "Calculable to mate or material — just play it",
   "Otherwise ask what you gain permanently",
   "A pawn for the initiative alone is often enough; a piece rarely is"
  ],
  "mode": "read"
 },
 {
  "id": "m-mateweb",
  "tier": 9,
  "title": "Building a mating net",
  "body": "Mate rarely comes from one move. It comes from taking away flight squares one at a time until there are none left. When you spot a king with only two escape squares, ask which piece could cover them both — that piece, not the checking one, is usually the key to the attack.",
  "points": [
   "Count the king's escape squares before you check",
   "Cover the flight squares, then deliver the check",
   "The quiet covering move is usually the hard one to see"
  ],
  "fen": "6k1/5ppp/8/8/8/8/5PPP/1R4K1 w - - 0 1",
  "mode": "solve",
  "task": "White to play. The back rank is the target — find mate in one.",
  "accept": [
   "Rb8"
  ],
  "hint": "His own pawns have sealed the escape squares. Use the empty rank.",
  "answer": "Rb8# — the classic back-rank mate."
 }
]
);})();
