// Taught opening lessons (tiers 6 and 7).
// Generated by tools/build-content.js — edit the data in tools/, then rebuild.
(function(){var C=window.KS_CONTENT=window.KS_CONTENT||{tiers:[],lessons:[],puzzles:[]};
C.lessons=C.lessons.concat(
[
 {
  "id": "o-principles",
  "tier": 6,
  "title": "What an opening is actually for",
  "body": "An opening is not a list of moves to memorise. It is a short race to three things: pawns in the centre, pieces off the back rank, and a king tucked away safely. If you achieve those by move ten or twelve you have had a good opening, whatever it was called. Everything below is just different ways of reaching that same finish line.",
  "points": [
   "Centre, development, king safety — in that order",
   "Knowing the plan beats knowing ten more moves",
   "If you forget the theory, fall back on the three goals"
  ],
  "mode": "explore",
  "note": "White has the full centre, three pieces out and can castle next move. That is a finished opening.",
  "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p3/2BPP3/2P2N2/PP3PPP/RNBQK2R b KQkq - 0 5"
 },
 {
  "id": "o-italian",
  "tier": 6,
  "title": "The Italian Game",
  "body": "1.e4 e5 2.Nf3 Nc6 3.Bc4 Bc5 is the most natural opening in chess: both sides take the centre, develop a knight, and point a bishop at the weakest square in the enemy camp, f7 and f2. It is the best first opening to own as White because every piece goes where you would put it anyway.",
  "points": [
   "Bc4 eyes f7 — the square only the king defends",
   "Follow with c3 and d4 to build a big centre",
   "Castle before you start anything on the kingside"
  ],
  "mode": "explore",
  "note": "Try c3 then d4. That is the Giuoco Piano plan: build the centre before you attack.",
  "fen": "r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4"
 },
 {
  "id": "o-giuoco-pianissimo",
  "tier": 6,
  "title": "Giuoco Pianissimo — the quiet Italian",
  "body": "Instead of the immediate d4, most strong players now prefer the slow build-up with d3, c3, Nbd2 and a later Nf1-g3. Nothing is resolved early, the centre stays locked, and the player who understands the plan out-manoeuvres the one who does not. This is the single most common structure in modern club chess.",
  "points": [
   "d3 first, then c3, Nbd2, Nf1, Ng3 — the knight tour",
   "Keep the centre closed while you improve pieces",
   "The h-pawn often runs up the board later"
  ],
  "mode": "explore",
  "note": "The knight is heading d2-f1-g3. Slow, but every piece ends up on a good square.",
  "fen": "r1bqk2r/ppp2ppp/2np1n2/2b1p3/2B1P3/2PP1N2/PP1N1PPP/R1BQK2R b KQkq - 1 6"
 },
 {
  "id": "o-evans",
  "tier": 6,
  "title": "The Evans Gambit",
  "body": "4.b4 offers a pawn for time. If Black takes, White plays c3 and d4 with a huge centre and both bishops raking the kingside while Black is still sorting out his pieces. It is one of the best practical gambits you can play at club level because the compensation is real and easy to handle.",
  "points": [
   "Give the b-pawn, gain c3 and d4 with tempo",
   "Aim the bishops at f7 and the long diagonal",
   "If Black gives the pawn back, you still keep the centre"
  ],
  "mode": "explore",
  "note": "After Bxb4 c3, the bishop must move again and White gets d4 in for free.",
  "fen": "r1bqk1nr/pppp1ppp/2n5/2b1p3/1PB1P3/5N2/P1PP1PPP/RNBQK2R b KQkq - 0 4"
 },
 {
  "id": "o-twoknights",
  "tier": 6,
  "title": "The Two Knights Defence",
  "body": "3...Nf6 ignores the threat to f7 and counter-attacks e4. It leads to the sharpest positions in the whole Italian complex, because White can lunge with 4.Ng5 attacking f7 twice. Black must know what he is doing here — but so must White.",
  "points": [
   "3...Nf6 hits e4 instead of defending f7",
   "4.Ng5 is crude but genuinely dangerous",
   "4.d4 and 4.d3 are the calmer main lines"
  ],
  "mode": "explore",
  "note": "Look at Ng5. Two attackers on f7, one defender. That is why this line is so sharp.",
  "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4"
 },
 {
  "id": "o-friedliver",
  "tier": 6,
  "title": "The Fried Liver Attack",
  "body": "After 4.Ng5 d5 5.exd5, Black's natural 5...Nxd5? allows 6.Nxf7!, dragging the king out to f7 where it is hunted in the open. Black must instead play the Fritz or Polerio with 5...Na5, hitting the bishop. Knowing which side of this line you are on wins a lot of games under 1400.",
  "points": [
   "5...Nxd5 is the mistake; 5...Na5 is the answer",
   "6.Nxf7 gives up a knight to expose the king",
   "Learn this once and never lose to it again"
  ],
  "mode": "solve",
  "task": "White to play. Punish 5...Nxd5.",
  "accept": [
   "Nxf7"
  ],
  "hint": "Black's king has to be the piece that recaptures.",
  "answer": "Nxf7! — the king is dragged to f7 and White follows with Qf3+.",
  "fen": "r1bqkb1r/ppp2ppp/2n5/3np1N1/2B5/8/PPPP1PPP/RNBQK2R w KQkq - 0 6"
 },
 {
  "id": "o-traxler",
  "tier": 6,
  "title": "The Traxler Counter-attack",
  "body": "Against 4.Ng5, Black can simply ignore f7 with 4...Bc5!?, meeting 5.Nxf7 with Bxf2+. Both kings come under fire at once and the game becomes a knife fight. It is not objectively better than the main lines, but it is extremely hard to meet over the board without preparation.",
  "points": [
   "Meets an attack on f7 with an attack on f2",
   "5.Bxf7+ is the safe reply; 5.Nxf7 invites chaos",
   "Only play it if you enjoy sharp, forcing positions"
  ],
  "mode": "explore",
  "note": "Black is ignoring the threat entirely. Count what happens after Nxf7 Bxf2+.",
  "fen": "r1bqk2r/pppp1ppp/2n2n2/2b1p1N1/2B1P3/8/PPPP1PPP/RNBQK2R w KQkq - 6 5"
 },
 {
  "id": "o-ruylopez",
  "tier": 6,
  "title": "The Ruy Lopez",
  "body": "3.Bb5 pins nothing yet but leans on the knight that defends e5. It is the most respected opening in chess and has been played at the top for two hundred years. White's long-term idea is to keep a small, permanent pull: better structure, more space, and pressure that never quite goes away.",
  "points": [
   "Pressure c6 to undermine the defender of e5",
   "3...a6 4.Ba4 is the main road — the Morphy Defence",
   "White plays c3 and d4 slowly, not all at once"
  ],
  "mode": "explore",
  "note": "Nxe5 does not win a pawn yet: after Qa5+ or d4 the pawn comes back. Check it yourself.",
  "fen": "r1bqkbnr/pppp1ppp/2n5/1B2p3/4P3/5N2/PPPP1PPP/RNBQK2R b KQkq - 3 3"
 },
 {
  "id": "o-ruy-closed",
  "tier": 6,
  "title": "Ruy Lopez: the Closed main line",
  "body": "3...a6 4.Ba4 Nf6 5.O-O Be7 6.Re1 b5 7.Bb3 d6 8.c3 O-O is the classical starting position of serious chess. White will play h3 and d4; Black will play Na5 and c5 to hit the centre. Both sides know the plan, and the game is decided by who executes it better.",
  "points": [
   "White: h3, d4, Nbd2-f1-g3",
   "Black: Na5 hits the bishop, then c5 hits the centre",
   "Do not rush d4 — prepare it with c3 and h3 first"
  ],
  "mode": "explore",
  "note": "This is the main position of the Closed Ruy. White's next plan is d4.",
  "fen": "r1bq1rk1/2p1bppp/p1np1n2/1p2p3/4P3/1BP2N1P/PP1P1PP1/RNBQR1K1 b - - 0 9"
 },
 {
  "id": "o-ruy-exchange",
  "tier": 6,
  "title": "Ruy Lopez: the Exchange Variation",
  "body": "4.Bxc6 dxc6 hands Black the bishop pair but wrecks his pawn structure: he has four pawns on the kingside against three, and his queenside majority can never make a healthy passed pawn. White's whole plan is to trade everything and win the king and pawn endgame.",
  "points": [
   "Black gets bishops; White gets a winning pawn structure",
   "White's plan: trade pieces, head for the endgame",
   "Do not play d4 too early — keep the structure fixed"
  ],
  "mode": "explore",
  "note": "Count the queenside pawns. Black has four against three but doubled — no passed pawn.",
  "fen": "r1bqkbnr/1pp2ppp/p1p5/4p3/4P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 0 5"
 },
 {
  "id": "o-ruy-berlin",
  "tier": 6,
  "title": "The Berlin Defence",
  "body": "3...Nf6 is the drawing weapon that took the world championship by storm. After 4.O-O Nxe4 5.d4 Nd6 6.Bxc6 dxc6 7.dxe5 Nf5 8.Qxd8+ Kxd8 the queens come off and Black's king sits on d8 in a famously stubborn endgame. Solid, but you must actually like endgames.",
  "points": [
   "Queens come off by move eight",
   "Black's king on d8 is safe, not weak",
   "White has the better structure; Black has the bishops"
  ],
  "mode": "explore",
  "note": "The famous Berlin endgame. No queens, no castling, and still perfectly playable for Black.",
  "fen": "r1bk1b1r/ppp2ppp/2p5/4Pn2/8/5N2/PPP2PPP/RNB2RK1 w - - 0 9"
 },
 {
  "id": "o-scotch",
  "tier": 6,
  "title": "The Scotch Game",
  "body": "3.d4 breaks the centre open immediately. After 3...exd4 4.Nxd4 White has a lead in development and an open game, and Black has no weaknesses but must play accurately. It is a superb practical choice because it avoids the vast theory of the Ruy Lopez.",
  "points": [
   "Opens the centre while you are better developed",
   "4...Bc5 and 4...Nf6 are the two main replies",
   "Do not chase with Nxc6 too early — it helps Black's centre"
  ],
  "mode": "explore",
  "note": "An open centre with a small development lead. Get castled and use it.",
  "fen": "r1bqkbnr/pppp1ppp/2n5/8/3NP3/8/PPP2PPP/RNBQKB1R b KQkq - 0 4"
 },
 {
  "id": "o-scotchgambit",
  "tier": 6,
  "title": "The Scotch Gambit",
  "body": "4.Bc4 instead of recapturing keeps the pawn offered and develops with threats against f7. If Black grabs with 4...Nf6 5.e5 or tries to hold everything, White generates fast play. It is an excellent surprise weapon that transposes into Italian structures when Black plays safely.",
  "points": [
   "Develop with threats instead of regaining the pawn",
   "f7 is the target again",
   "Transposes to the Italian if Black plays ...Bc5"
  ],
  "mode": "explore",
  "note": "White is a pawn down and does not care — every piece comes out hitting something.",
  "fen": "r1bqkbnr/pppp1ppp/2n5/8/2BpP3/5N2/PPP2PPP/RNBQK2R b KQkq - 1 4"
 },
 {
  "id": "o-fourknights",
  "tier": 6,
  "title": "The Four Knights Game",
  "body": "1.e4 e5 2.Nf3 Nc6 3.Nc3 Nf6 is symmetry at its most honest. It has a reputation for dullness that it does not deserve: the Scotch Four Knights with 4.d4 and the Spanish Four Knights with 4.Bb5 both give real play. A perfect opening while you are learning, because nothing can go badly wrong.",
  "points": [
   "Both sides simply develop knights first",
   "4.Bb5 or 4.d4 to break the symmetry",
   "Very hard to lose quickly — good for learning"
  ],
  "mode": "explore",
  "note": "Perfect symmetry. White must break it to play for something — try d4 or Bb5.",
  "fen": "r1bqkb1r/pppp1ppp/2n2n2/4p3/4P3/2N2N2/PPPP1PPP/R1BQKB1R w KQkq - 4 4"
 },
 {
  "id": "o-petrov",
  "tier": 6,
  "title": "The Petrov (Russian) Defence",
  "body": "2...Nf6 counter-attacks instead of defending e5. After 3.Nxe5 d6! (never 3...Nxe4? 4.Qe2) 4.Nf3 Nxe4 the position is symmetrical and extremely solid. It is the classical answer to 1.e4 for players who want a quiet life with Black.",
  "points": [
   "3...d6 first — kicking the knight before recapturing",
   "3...Nxe4? 4.Qe2 wins material on the e-file",
   "Very solid, slightly drawish, hard to beat"
  ],
  "mode": "explore",
  "note": "Black kicked the knight first, then took. Playing Nxe4 immediately loses to Qe2.",
  "fen": "rnbqkb1r/ppp2ppp/3p4/8/4n3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 0 5"
 },
 {
  "id": "o-petrov-trap",
  "tier": 6,
  "title": "The Petrov trap: why ...d6 comes first",
  "body": "If Black recaptures immediately with 3...Nxe4?, White plays 4.Qe2! and suddenly the knight on e4 is pinned against the king along the e-file. Black cannot hold it, and 4...Nf6?? even loses the queen to 5.Nc6+. This is the single most punished mistake in the whole Petrov.",
  "points": [
   "Qe2 pins the knight down the open e-file",
   "4...Nf6 loses to a discovered check winning the queen",
   "Always insert ...d6 before recapturing"
  ],
  "mode": "solve",
  "task": "White to play. Punish the immediate recapture.",
  "accept": [
   "Qe2"
  ],
  "hint": "Line up against the knight and the king on the same file.",
  "answer": "Qe2! — the knight is pinned and cannot be saved.",
  "fen": "rnbqkb1r/pppp1ppp/8/4N3/4n3/8/PPPP1PPP/RNBQKB1R w KQkq - 0 4"
 },
 {
  "id": "o-philidor",
  "tier": 6,
  "title": "The Philidor Defence",
  "body": "2...d6 defends e5 with a pawn but shuts in the dark-squared bishop. It is passive but genuinely solid, and the Hanham setup with ...Nbd7, ...Be7 and ...c6 is very hard to break down. Black must simply accept less space and wait for a chance to play ...d5.",
  "points": [
   "Solid but cramped — the bishop on f8 needs patience",
   "Aim for the ...d5 break at the right moment",
   "Beware Ng5 ideas hitting f7 while you are undeveloped"
  ],
  "mode": "explore",
  "note": "The Hanham setup. Cramped, but there are no weaknesses to attack.",
  "fen": "r1bqk2r/pppnbppp/3p1n2/4p3/2BPP3/2N2N2/PPP2PPP/R1BQK2R w KQkq - 5 6"
 },
 {
  "id": "o-legal",
  "tier": 6,
  "title": "Légal's Mate",
  "body": "The oldest trap in the book, and it still works. In a Philidor structure where Black pins the f3-knight with ...Bg4, White can sometimes ignore the pin entirely: the queen is offered, and if Black takes it, three minor pieces deliver mate. Everybody should see this once.",
  "points": [
   "The pin on f3 is not always real",
   "Nxe5 offers the queen; Bxf7+ and Nd5 finish it",
   "Check whether a pin actually stops the move"
  ],
  "mode": "solve",
  "task": "White to play. Ignore the pin and win material.",
  "accept": [
   "Nxe5"
  ],
  "hint": "The knight is pinned — but is the pin worth more than what the knight can take?",
  "answer": "Nxe5! — if dxe5 then Bxf7+ Ke7 Nd5#. Otherwise White is just a pawn up.",
  "fen": "rn1qkbnr/ppp2p1p/3p2p1/4p3/2B1P1b1/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 0 5"
 },
 {
  "id": "o-kingsgambit",
  "tier": 6,
  "title": "The King's Gambit",
  "body": "2.f4 is the great romantic opening: White offers a pawn to blow open the f-file and seize the centre with d4. It is objectively risky because the king gets draughty, but at club level it wins far more than it loses because Black is rarely prepared for the chaos.",
  "points": [
   "Offers the f-pawn for the centre and the f-file",
   "3.Nf3 stops the annoying ...Qh4+",
   "Get castled fast — your king is the weak point too"
  ],
  "mode": "explore",
  "note": "Nf3 first, always: it takes the h4 check away before Black can play it.",
  "fen": "rnbqkbnr/pppp1ppp/8/8/4Pp2/5N2/PPPP2PP/RNBQKB1R b KQkq - 1 3"
 },
 {
  "id": "o-vienna",
  "tier": 6,
  "title": "The Vienna Game",
  "body": "2.Nc3 is a flexible, underrated move. It defends e4, prepares f4 in a safer version of the King's Gambit, and keeps the option of a quiet Bc4 setup. Because it is far less common than 2.Nf3, most opponents leave their preparation behind on move two.",
  "points": [
   "Supports a later f4 without the King's Gambit risk",
   "Bc4 and Qf3 ideas hit f7 quickly",
   "Rare enough that opponents are on their own early"
  ],
  "mode": "explore",
  "note": "The Vienna Gambit. Much safer than the King's Gambit because Nc3 is already useful.",
  "fen": "rnbqkb1r/pppp1ppp/5n2/4p3/4PP2/2N5/PPPP2PP/R1BQKBNR b KQkq - 0 3"
 },
 {
  "id": "o-bishops",
  "tier": 6,
  "title": "The Bishop's Opening",
  "body": "2.Bc4 goes straight for f7 before committing the knight. It usually transposes into the Vienna or the Italian, but the move order dodges the Petrov and the Two Knights lines White may not want. A tidy, low-theory way to reach good positions.",
  "points": [
   "Hits f7 on move two",
   "Transposes into Vienna or Italian structures",
   "Sidesteps the Petrov entirely"
  ],
  "mode": "explore",
  "note": "A quiet Italian-style setup reached by a different route.",
  "fen": "rnbqkb1r/pp1p1ppp/2p2n2/4p3/2B1P3/3P1N2/PPP2PPP/RNBQK2R b KQkq - 1 4"
 },
 {
  "id": "o-danish",
  "tier": 6,
  "title": "The Danish Gambit",
  "body": "1.e4 e5 2.d4 exd4 3.c3 offers one pawn, and after 3...dxc3 4.Bc4 cxb2 5.Bxb2 a second, for two raking bishops on the long diagonals and a massive development lead. Unsound against perfect defence, devastating against anything less.",
  "points": [
   "Two pawns for two monster bishops",
   "Both bishops stare at f7 and g7",
   "If Black declines with ...d5, play exd5 and stay calm"
  ],
  "mode": "explore",
  "note": "Two pawns down, but look at those diagonals. Black cannot develop comfortably.",
  "fen": "rnbqkbnr/pppp1ppp/8/8/2B1P3/8/PB3PPP/RN1QK1NR b KQkq - 0 5"
 },
 {
  "id": "o-sicilian",
  "tier": 6,
  "title": "The Sicilian Defence",
  "body": "1...c5 is the most popular and most successful answer to 1.e4. Black declines the symmetrical game, trades a wing pawn for a centre pawn after d4, and gets a half-open c-file to attack down. Statistically it scores better for Black than anything else.",
  "points": [
   "Trades a c-pawn for White's d-pawn — a better pawn",
   "The half-open c-file is Black's attacking route",
   "Unbalanced from move one: winning chances for both"
  ],
  "mode": "explore",
  "note": "The Open Sicilian. Black's c-file is open and pointing at c3 — that is the plan.",
  "fen": "rnbqkb1r/pp2pppp/3p1n2/8/3NP3/2N5/PPP2PPP/R1BQKB1R b KQkq - 2 5"
 },
 {
  "id": "o-najdorf",
  "tier": 6,
  "title": "The Najdorf Sicilian",
  "body": "5...a6 is the most analysed move in chess. The little pawn move takes b5 away from White's pieces and prepares ...e5 or ...e6 with a flexible, aggressive setup. It was Fischer's and Kasparov's main weapon, and it demands real study — but the ideas are learnable.",
  "points": [
   "...a6 controls b5 before deciding on the centre",
   "Prepares ...e5 hitting the knight, or a Scheveningen ...e6",
   "White's main tries: 6.Bg5, 6.Be3, 6.Bc4, 6.h3"
  ],
  "mode": "explore",
  "note": "A quiet-looking pawn move with a purpose: no White piece will ever use b5.",
  "fen": "rnbqkb1r/1p2pppp/p2p1n2/8/3NP3/2N5/PPP2PPP/R1BQKB1R w KQkq - 0 6"
 },
 {
  "id": "o-dragon",
  "tier": 6,
  "title": "The Dragon Sicilian",
  "body": "Black fianchettoes with ...g6 and ...Bg7, aiming the bishop straight down the long diagonal at White's queenside. White's standard answer is the Yugoslav Attack: castle queenside, push h4-h5, and try to mate first. Both sides attack opposite kings and the faster one wins.",
  "points": [
   "The g7 bishop is the whole opening — never trade it cheaply",
   "Yugoslav Attack: Be3, Qd2, O-O-O, h4-h5, Bh6",
   "A pure race: count tempi, not material"
  ],
  "mode": "explore",
  "note": "White castles queenside and storms the h-file; Black plays ...Rc8 and ...Qa5. A race.",
  "fen": "rnbq1rk1/pp2ppbp/3p1np1/8/3NP3/2N1BP2/PPPQ2PP/R3KB1R b KQ - 2 8"
 },
 {
  "id": "o-acceldragon",
  "tier": 6,
  "title": "The Accelerated Dragon",
  "body": "Playing ...g6 a move earlier, without ...d6, lets Black get ...d5 in one go rather than two. The price is allowing the Maroczy Bind with c4, which grips d5 and takes the fun out of Black's position. Knowing which one you are heading for is the whole battle.",
  "points": [
   "Saves a tempo by skipping ...d6",
   "Allows the Maroczy Bind with c2-c4",
   "Black's freeing break is ...d5 in one move"
  ],
  "mode": "explore",
  "note": "The Maroczy Bind. Pawns on c4 and e4 clamp d5 — Black will be squeezed for space.",
  "fen": "r1bqkbnr/pp1ppp1p/2n3p1/8/2PNP3/8/PP3PPP/RNBQKB1R b KQkq - 0 5"
 },
 {
  "id": "o-sveshnikov",
  "tier": 6,
  "title": "The Sveshnikov Sicilian",
  "body": "5...e5 looks like it simply wrecks Black's structure, leaving a hole on d5 and a backward d-pawn. In return Black gets fast piece play, the bishop pair after ...Bxd5, and genuine attacking chances. It is a modern main line precisely because activity outweighs the weakness.",
  "points": [
   "Accepts a permanent hole on d5 for piece activity",
   "...b5 and ...Bg7 follow, fighting for the dark squares",
   "Concrete and forcing — you must know the lines"
  ],
  "mode": "explore",
  "note": "d5 is a permanent hole and Black does not care. Activity is the compensation.",
  "fen": "r1bqkb1r/5ppp/p1np1n2/1p2p1B1/4P3/N1N5/PPP2PPP/R2QKB1R w KQkq - 0 9"
 },
 {
  "id": "o-alapin",
  "tier": 6,
  "title": "The Alapin — 2.c3 against the Sicilian",
  "body": "2.c3 prepares d4 so that White recaptures with the pawn and keeps a big centre, avoiding the entire Open Sicilian. It is the most practical anti-Sicilian there is: one clear plan, very little theory, and Black's typical Sicilian knowledge is simply not relevant.",
  "points": [
   "Supports d4 so you recapture with a pawn, not a piece",
   "Black's best: 2...d5 or 2...Nf6 hitting e4",
   "Cuts out thousands of pages of Sicilian theory"
  ],
  "mode": "explore",
  "note": "White has the ideal pawn centre and will gain time on the queen with Nf3 and Be2.",
  "fen": "rnb1kbnr/pp2pppp/8/2pq4/3P4/2P5/PP3PPP/RNBQKBNR b KQkq - 0 4"
 },
 {
  "id": "o-smithmorra",
  "tier": 6,
  "title": "The Smith-Morra Gambit",
  "body": "2.d4 cxd4 3.c3 offers a pawn to open the c- and d-files fast. White's pieces flow out to natural squares — Bc4, Nf3, O-O, Qe2, Rd1 — and Black must defend precisely from move five. Below 1800 it is one of the highest-scoring gambits in the game.",
  "points": [
   "One pawn for two open files and a huge lead",
   "Standard setup: Bc4, Nc3, Nf3, O-O, Qe2, Rfd1, Rac1",
   "The pressure on d6 and f7 is constant"
  ],
  "mode": "explore",
  "note": "Every White piece is on a natural square with open files. That is the pawn's value.",
  "fen": "r1bqkbnr/pp3ppp/2npp3/8/2B1P3/2N2N2/PP3PPP/R1BQ1RK1 b kq - 1 7"
 },
 {
  "id": "o-grandprix",
  "tier": 6,
  "title": "The Grand Prix Attack",
  "body": "Against the Sicilian, White plays f4, Nf3, Bc4 or Bb5, and castles, then throws the kingside pawns forward. It ignores the centre somewhat but produces a fast, thematic attack that is very easy to play and very unpleasant to meet without preparation.",
  "points": [
   "f4 and Nf3 first, then decide where the bishop goes",
   "Attack with f5, Qe1-h4 and Rf3-h3",
   "Low theory, high danger — ideal for fast time controls"
  ],
  "mode": "explore",
  "note": "White's plan is simple: f5 next, then swing the queen and rook to the h-file.",
  "fen": "r1bqk1nr/pp1p1pbp/2n1p1p1/2p5/2B1PP2/2N2N2/PPPP2PP/R1BQ1RK1 b kq - 1 6"
 },
 {
  "id": "o-closedsicilian",
  "tier": 6,
  "title": "The Closed Sicilian",
  "body": "White declines to open the centre at all: Nc3, g3, Bg2, d3, f4 and a slow kingside build-up. The game becomes a manoeuvring battle where understanding beats memory. Spassky used it at the very top, and it is a fine choice if you dislike sharp theory.",
  "points": [
   "No early d4 — the centre stays closed",
   "Bg2, d3, f4, Nf3, then f5 and a kingside attack",
   "Plans matter far more than move order here"
  ],
  "mode": "explore",
  "note": "Mirror-image fianchettos. White will play f5; Black will play ...b5 and ...Rb8.",
  "fen": "r1bqk1nr/pp2ppbp/2np2p1/2p5/4PP2/2NP2P1/PPP3BP/R1BQK1NR b KQkq - 0 6"
 },
 {
  "id": "o-french",
  "tier": 6,
  "title": "The French Defence",
  "body": "1...e6 prepares ...d5 to challenge the centre head-on. Black accepts one long-term problem — the light-squared bishop is shut in behind his own pawns — in exchange for a rock-solid structure and a clear plan of attacking White's centre with ...c5 and ...f6.",
  "points": [
   "Very solid, but the c8 bishop is the problem child",
   "Black's breaks are ...c5 and later ...f6",
   "White gets space; Black gets a target"
  ],
  "mode": "explore",
  "note": "Black's light-squared bishop is behind the pawn chain. Solving that is the whole opening.",
  "fen": "rnbqkbnr/ppp2ppp/4p3/3p4/3PP3/8/PPP2PPP/RNBQKBNR w KQkq - 0 3"
 },
 {
  "id": "o-french-advance",
  "tier": 6,
  "title": "French: the Advance Variation",
  "body": "3.e5 grabs space and locks the centre. The pawn chain d4-e5 points at Black's kingside, so White attacks there; Black's chain e6-d5 points at the queenside, so he attacks the base of White's chain with ...c5 and ...Qb6. Chains decide the plans.",
  "points": [
   "Attack the base of the enemy chain, not the head",
   "White: f4, Nf3, and pressure on the kingside",
   "Black: ...c5, ...Qb6, ...Nc6 hitting d4"
  ],
  "mode": "explore",
  "note": "Black is piling on d4 — the base of White's chain. That is the correct target.",
  "fen": "r1b1kbnr/pp3ppp/1qn1p3/2ppP3/3P4/2P2N2/PP3PPP/RNBQKB1R w KQkq - 3 6"
 },
 {
  "id": "o-french-tarrasch",
  "tier": 6,
  "title": "French: the Tarrasch",
  "body": "3.Nd2 keeps the option of c3 and avoids the pin that 3.Nc3 allows with ...Bb4. It is the quiet, positional way to meet the French, favoured by Karpov, and it leads to small stable advantages rather than sharp complications.",
  "points": [
   "Nd2 avoids ...Bb4 pinning the knight",
   "Keeps c3 available to support d4",
   "Positional and low-risk — a long squeeze"
  ],
  "mode": "explore",
  "note": "White has more space and a solid chain. The plan is slow pressure, not a quick attack.",
  "fen": "rnbqkb1r/pp1n1ppp/4p3/2ppP3/3P4/2PB4/PP1N1PPP/R1BQK1NR b KQkq - 0 6"
 },
 {
  "id": "o-french-winawer",
  "tier": 6,
  "title": "French: the Winawer",
  "body": "3.Nc3 Bb4 pins the knight and threatens the centre. After 4.e5 c5 5.a3 Bxc3+ 6.bxc3 White gets doubled pawns and the bishop pair with a big centre; Black gets a permanent structural target on c3. It is one of the most unbalanced openings there is.",
  "points": [
   "Black trades bishop for knight to damage the structure",
   "White gets the bishop pair and attacking chances",
   "Black targets the weak c3 and doubled pawns"
  ],
  "mode": "explore",
  "note": "Doubled c-pawns for the bishop pair. Completely unbalanced — both sides play for a win.",
  "fen": "rnbqk1nr/pp3ppp/4p3/2ppP3/3P4/P1P5/2P2PPP/R1BQKBNR b KQkq - 0 6"
 },
 {
  "id": "o-carokann",
  "tier": 6,
  "title": "The Caro-Kann Defence",
  "body": "1...c6 prepares ...d5 just like the French, but keeps the c8 bishop's diagonal open so it can develop to f5 or g4 before the pawn chain closes. It is the solid, low-risk answer to 1.e4 — fewer winning attempts, far fewer disasters.",
  "points": [
   "Like the French, but the bishop gets out first",
   "Develop ...Bf5 before playing ...e6",
   "Extremely solid; excellent endgame structures"
  ],
  "mode": "explore",
  "note": "The bishop is outside the pawn chain — exactly what the French player wishes he had.",
  "fen": "rn1qkbnr/pp2pppp/2p5/5b2/3PN3/8/PPP2PPP/R1BQKBNR w KQkq - 1 5"
 },
 {
  "id": "o-carokann-advance",
  "tier": 6,
  "title": "Caro-Kann: the Advance Variation",
  "body": "3.e5 Bf5 is the modern main line. Black gets his bishop out and then builds with ...e6, ...c5 and ...Nc6, chipping at d4. White gains space and often plays Nf3, Be2 and O-O, or the sharp h4-h5 trying to trap the bishop on the kingside.",
  "points": [
   "...Bf5 first — always, before ...e6",
   "White's h4-h5 is the critical try against the bishop",
   "Then ...c5 hits the base of the chain"
  ],
  "mode": "explore",
  "note": "Bishop outside the chain, then ...c5 at the base. The Caro-Kann plan in two moves.",
  "fen": "rn1qkbnr/pp3ppp/4p3/2ppPb2/3P4/5N2/PPP1BPPP/RNBQK2R w KQkq - 0 6"
 },
 {
  "id": "o-carokann-panov",
  "tier": 6,
  "title": "Caro-Kann: the Panov Attack",
  "body": "3.exd5 cxd5 4.c4 turns the game into an isolated queen's pawn structure, the same one that arises from the Nimzo-Indian and the Tarrasch. White gets active pieces and attacking chances; Black gets a target to blockade. It is the most aggressive anti-Caro line.",
  "points": [
   "Creates an isolated d-pawn position with the attack",
   "White: pieces first, Ne5 and Bg5 pressure",
   "Black: blockade d5 and trade into the endgame"
  ],
  "mode": "explore",
  "note": "White will end up with an isolated d-pawn — dynamic in the middlegame, weak in the endgame.",
  "fen": "rnbqkb1r/pp3ppp/4pn2/3p4/2PP4/2N2N2/PP3PPP/R1BQKB1R b KQkq - 1 6"
 },
 {
  "id": "o-scandinavian",
  "tier": 6,
  "title": "The Scandinavian Defence",
  "body": "1...d5 challenges the centre at once. After 2.exd5 Qxd5 3.Nc3 the queen is chased, but she settles on a5 or d6 quite comfortably and Black's position is simple: ...Nf6, ...Bf5 or ...Bg4, ...e6, ...c6 and castle. One setup against everything makes it perfect for a first Black opening.",
  "points": [
   "One reliable setup you can play every game",
   "Qa5 and Qd6 are both sound queen squares",
   "...Bg4 or ...Bf5 before ...e6, as always"
  ],
  "mode": "explore",
  "note": "The queen looks exposed but there is no way to attack her profitably. A very easy system.",
  "fen": "rn2kb1r/ppp1pppp/5n2/q7/3P2b1/2N2N2/PPP2PPP/R1BQKB1R w KQkq - 3 6"
 },
 {
  "id": "o-alekhine",
  "tier": 6,
  "title": "Alekhine's Defence",
  "body": "1...Nf6 provokes White into chasing the knight with pawns. Black deliberately lets White build a huge centre, then attacks it with ...d6, ...c5 and ...Nc6, betting that the overextended pawns become weak. It is hypermodern chess in its purest form.",
  "points": [
   "Invites the centre forward so it can be attacked",
   "The Four Pawns Attack is White's most testing try",
   "Black must counter-punch quickly or be squashed"
  ],
  "mode": "explore",
  "note": "White's centre looks enormous. Black's whole plan is to prove it is a liability.",
  "fen": "rnbqkb1r/ppp1pp1p/3p2p1/3nP3/2BP4/5N2/PPP2PPP/RNBQK2R b KQkq - 1 5"
 },
 {
  "id": "o-pirc",
  "tier": 6,
  "title": "The Pirc Defence",
  "body": "1...d6 and 2...Nf6 with ...g6 and ...Bg7 gives White the centre and attacks it later from a distance. Black's position is flexible and hard to attack directly, but he must not drift — the counter-punch with ...c5 or ...e5 has to come.",
  "points": [
   "Fianchetto first, strike at the centre second",
   "The Austrian Attack with f4 is White's sharpest",
   "Black must play ...c5 or ...e5 before being squeezed"
  ],
  "mode": "explore",
  "note": "The Austrian Attack. White has four centre pawns; Black must hit back fast.",
  "fen": "rnbq1rk1/ppp1ppbp/3p1np1/8/3PPP2/2N2N2/PPP3PP/R1BQKB1R w KQ - 3 6"
 },
 {
  "id": "o-modern",
  "tier": 6,
  "title": "The Modern Defence",
  "body": "1...g6 delays ...Nf6, keeping maximum flexibility and dodging some of White's sharpest Pirc lines. Black can choose later between ...d6, ...c5 or even ...a6 and ...b5 setups. Very flexible, but it demands understanding rather than memorised moves.",
  "points": [
   "Fianchetto immediately, commit to nothing else",
   "Can transpose to the Pirc, or stay independent",
   "Understanding over memorisation"
  ],
  "mode": "explore",
  "note": "Black keeps every option open — ...b5, ...c6, ...Nf6 or ...e5 are all still available.",
  "fen": "rnbqk1nr/1pp1ppbp/p2p2p1/8/3PP3/2N1B3/PPP2PPP/R2QKBNR w KQkq - 0 5"
 },
 {
  "id": "o-antisicilian-bb5",
  "tier": 6,
  "title": "The Rossolimo and Moscow",
  "body": "3.Bb5 against ...Nc6 (Rossolimo) or 3.Bb5+ against ...d6 (Moscow) sidesteps the Open Sicilian entirely. White trades on c6 to damage Black's structure, or keeps the bishop and plays a quiet Ruy-like game. Very popular at the top for exactly this reason.",
  "points": [
   "Avoids all the Najdorf and Dragon preparation",
   "Bxc6 doubles Black's pawns permanently",
   "Low theory, sound positions, easy plans"
  ],
  "mode": "explore",
  "note": "Black has the bishop pair; White has the better pawns. A classic structural trade-off.",
  "fen": "r1bqkbnr/pp2pp1p/2p3p1/2p5/4P3/3P1N2/PPP2PPP/RNBQK2R b KQkq - 0 5"
 },
 {
  "id": "o-d4-intro",
  "tier": 7,
  "title": "Why 1.d4 feels different",
  "body": "1.e4 opens lines immediately and the game often catches fire by move ten. 1.d4 is slower: the d-pawn is already defended by the queen, so positions stay closed longer and plans matter more than tactics. If you prefer manoeuvring to shootouts, this is your move.",
  "points": [
   "d4 is defended from the start — e4 is not",
   "Closed positions, longer plans, fewer early accidents",
   "Both are equally good — pick the one that suits you"
  ],
  "mode": "explore",
  "note": "The Queen's Gambit. Not really a gambit — White regains the pawn whenever he wants.",
  "fen": "rnbqkbnr/ppp1pppp/8/3p4/2PP4/8/PP2PPPP/RNBQKBNR b KQkq - 0 2"
 },
 {
  "id": "o-qgd",
  "tier": 7,
  "title": "The Queen's Gambit Declined",
  "body": "2...e6 supports d5 with a pawn and builds the soundest structure in chess. The cost, exactly as in the French, is the light-squared bishop on c8. Black's whole opening plan is to solve that bishop, usually with ...b6 and ...Bb7 or with a timely ...dxc4 and ...Bd7-c6.",
  "points": [
   "The most solid answer to 1.d4 there is",
   "Problem piece: the c8 bishop, again",
   "Freeing moves: ...c5, ...dxc4, or ...b6 and ...Bb7"
  ],
  "mode": "explore",
  "note": "A textbook QGD. Black is solid; the only question is how the c8 bishop gets out.",
  "fen": "rnbq1rk1/ppp1bppp/4pn2/3p2B1/2PP4/2N1PN2/PP3PPP/R2QKB1R b KQ - 2 6"
 },
 {
  "id": "o-qgd-exchange",
  "tier": 7,
  "title": "QGD: the Exchange and the minority attack",
  "body": "After cxd5 exd5 White gets a clear, permanent plan: push b4-b5 on the queenside, where he has two pawns against three. When the pawns trade, Black is left with a weak c-pawn on a half-open file. This is the classic minority attack, and it wins a lot of games on autopilot.",
  "points": [
   "Two pawns attacking three, to create one weakness",
   "b4-b5, then bxc6 leaving a backward c-pawn",
   "Black counters with play in the centre or on the kingside"
  ],
  "mode": "explore",
  "note": "White's plan is b4, a4, b5. Fewer pawns attacking more — that is the point.",
  "fen": "r1bqr1k1/pp1nbppp/2p2n2/3p2B1/3P4/2NBPN2/PPQ2PPP/R4RK1 b - - 5 10"
 },
 {
  "id": "o-qga",
  "tier": 7,
  "title": "The Queen's Gambit Accepted",
  "body": "2...dxc4 takes the pawn but does not try to keep it: after 3.Nf3 Nf6 4.e3 e6 5.Bxc4 White simply recaptures having gained the centre. Black's compensation is fast development and the freeing break ...c5. Practical, sound, and much less theoretical than the QGD.",
  "points": [
   "Take the pawn, but never try to hold it with ...b5",
   "Black's equaliser is the ...c5 break",
   "Do not grab and then fall behind in development"
  ],
  "mode": "explore",
  "note": "Black gave up the centre but is hitting back with ...c5 immediately. That is the deal.",
  "fen": "rnbqkb1r/pp3ppp/4pn2/2p5/2BP4/4PN2/PP3PPP/RNBQK2R w KQkq - 0 6"
 },
 {
  "id": "o-slav",
  "tier": 7,
  "title": "The Slav Defence",
  "body": "2...c6 supports d5 with the c-pawn instead of the e-pawn, which leaves the c8 bishop free to develop to f5 or g4. That single difference from the QGD solves Black's worst problem, which is why the Slav is one of the most trusted defences at every level.",
  "points": [
   "Supports d5 without burying the bishop",
   "Get ...Bf5 in before playing ...e6",
   "Extremely solid — a lifetime defence"
  ],
  "mode": "explore",
  "note": "Compare with the QGD: same pawn on d5, but the bishop is already outside the chain.",
  "fen": "rn1qkb1r/pp2pppp/2p2n2/5b2/P1pP4/2N2N2/1P2PPPP/R1BQKB1R w KQkq - 1 6"
 },
 {
  "id": "o-semislav",
  "tier": 7,
  "title": "The Semi-Slav",
  "body": "Playing both ...c6 and ...e6 builds a fortress around d5 and prepares the thematic ...dxc4 followed by ...b5 and ...c5, finally freeing the position with a queenside pawn storm. It is rich, double-edged and theoretical — the Botvinnik and Meran lines are among the sharpest in chess.",
  "points": [
   "...c6 and ...e6 together: maximum solidity",
   "The plan is ...dxc4 then ...b5 and ...c5",
   "Very sharp main lines — study before you play it"
  ],
  "mode": "explore",
  "note": "The Meran. Black has finally freed himself with ...b5 and will follow with ...c5.",
  "fen": "r1bqkb1r/p2n1ppp/2p1pn2/1p6/2BP4/2N1PN2/PP3PPP/R1BQK2R w KQkq - 0 8"
 },
 {
  "id": "o-london",
  "tier": 7,
  "title": "The London System",
  "body": "d4, Bf4, e3, Nf3, c3, Bd3, Nbd2 and castle — the same setup against almost anything Black plays. It is the ultimate low-maintenance opening: you never get surprised, you never get mated in fifteen moves, and you always know your plan. Ideal while you spend your study time on tactics and endgames.",
  "points": [
   "One setup against nearly everything",
   "Get the bishop out to f4 before playing e3",
   "Plans: Ne5, a kingside build-up, or a queenside minority attack"
  ],
  "mode": "explore",
  "note": "The full London setup. Every piece is on its square and nothing can go badly wrong.",
  "fen": "rnbq1rk1/pp2bppp/4pn2/2pp4/3P1B2/2PBPN2/PP1N1PPP/R2QK2R b KQ - 0 7"
 },
 {
  "id": "o-colle",
  "tier": 7,
  "title": "The Colle and the Torre",
  "body": "Two more system openings. The Colle plays d4, Nf3, e3, Bd3, c3 and Nbd2, then blows the centre open with e3-e4 at the right moment. The Torre plays Bg5 instead, pinning the f6-knight. Both are cheap to learn and give perfectly sound positions.",
  "points": [
   "Colle: build quietly, then break with e4",
   "Torre: Bg5 pinning, with Nbd2 and c3 behind it",
   "Systems free your study time for tactics"
  ],
  "mode": "explore",
  "note": "The Colle break. White spent eight quiet moves preparing exactly this one.",
  "fen": "r1bq1rk1/pp2bppp/2n1pn2/2pp4/3PP3/2PB1N2/PP1N1PPP/R1BQ1RK1 b - - 0 8"
 },
 {
  "id": "o-trompowsky",
  "tier": 7,
  "title": "The Trompowsky Attack",
  "body": "2.Bg5 on move two, before Black has committed to anything. White is happy to trade bishop for knight and play against the doubled pawns, or to retreat and play a normal game. It takes almost no theory and drags opponents out of their preparation instantly.",
  "points": [
   "Hits f6 before Black can choose a defence",
   "Bxf6 doubling the pawns is a real plan, not a concession",
   "Extremely low theory — high practical value"
  ],
  "mode": "explore",
  "note": "White traded bishop for knight to grab the centre with e4. Black has the bishop pair.",
  "fen": "rnb1kb1r/pppp1pp1/4pq1p/8/3PP3/8/PPP2PPP/RN1QKBNR w KQkq - 0 5"
 },
 {
  "id": "o-nimzo",
  "tier": 7,
  "title": "The Nimzo-Indian Defence",
  "body": "3...Bb4 pins the c3-knight, the piece that guards e4. Black is willing to trade a bishop for a knight to control the light squares and damage White's structure. It is the most respected defence to 1.d4 and has never been refuted in a century of trying.",
  "points": [
   "Pins the knight guarding e4",
   "Trading on c3 doubles White's pawns permanently",
   "Black fights for control, not space"
  ],
  "mode": "explore",
  "note": "Nc3 is the only piece holding e4. That is exactly why the bishop pins it.",
  "fen": "rnbqk2r/pppp1ppp/4pn2/8/1bPP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 2 4"
 },
 {
  "id": "o-queensindian",
  "tier": 7,
  "title": "The Queen's Indian Defence",
  "body": "When White avoids the Nimzo with 3.Nf3, Black plays 3...b6 and fianchettoes, fighting for e4 with the bishop instead of the pin. Solid, flexible, and very hard to attack — it was Karpov's favourite and it still holds up perfectly.",
  "points": [
   "Bishop to b7 fights for e4 from a distance",
   "Very solid; almost no forced losses",
   "Often combined with ...Bb4+ ideas anyway"
  ],
  "mode": "explore",
  "note": "Two fianchettoed bishops staring at each other down the long diagonal.",
  "fen": "rn1q1rk1/pbppbppp/1p2pn2/8/2PP4/5NP1/PP2PPBP/RNBQ1RK1 w - - 5 7"
 },
 {
  "id": "o-bogo",
  "tier": 7,
  "title": "The Bogo-Indian Defence",
  "body": "3...Bb4+ is a simple, practical way to meet 3.Nf3. The check forces White to block with Bd2 or Nbd2, after which Black completes development comfortably. It avoids enormous amounts of Queen's Indian theory and leads to sound, quiet positions.",
  "points": [
   "A check that gains time and simplifies your choices",
   "Much less theory than the Queen's Indian",
   "Aim for ...d6 and ...e5, or ...d5 for a QGD structure"
  ],
  "mode": "explore",
  "note": "Black will play ...e5 next and get a comfortable, solid game with no theory to remember.",
  "fen": "rnb2rk1/ppp1qppp/3ppn2/8/1bPP4/5NP1/PP1BPPBP/RN1QK2R w KQ - 0 7"
 },
 {
  "id": "o-kid",
  "tier": 7,
  "title": "The King's Indian Defence",
  "body": "Black gives White a huge centre, fianchettoes, castles, and then attacks it with ...e5 and a kingside pawn storm. It is the most aggressive answer to 1.d4: Black often ignores the queenside entirely and races for mate. Not for the faint-hearted, and enormously fun.",
  "points": [
   "Let White build the centre, then hit it with ...e5",
   "Classic race: White attacks queenside, Black attacks kingside",
   "The g7 bishop wakes up when the centre opens"
  ],
  "mode": "explore",
  "note": "The main tabiya. White plays d5 and attacks on the queenside; Black plays ...f5 and mates.",
  "fen": "rnbq1rk1/ppp2pbp/3p1np1/4p3/2PPP3/2N2N2/PP2BPPP/R1BQK2R w KQ - 0 7"
 },
 {
  "id": "o-grunfeld",
  "tier": 7,
  "title": "The Grünfeld Defence",
  "body": "3...d5 strikes at the centre instead of surrounding it. After cxd5 Nxd5 and the trade on c3, White builds a big pawn centre and Black spends the rest of the game proving it is overextended, with ...c5, ...Bg7 and pressure down the long diagonal.",
  "points": [
   "Trade off centre pawns, then attack what is left",
   "The g7 bishop and ...c5 target d4 together",
   "Hypermodern: the centre is a target, not a goal"
  ],
  "mode": "explore",
  "note": "White's centre is imposing. Black is already chipping at it with ...c5 and the bishop.",
  "fen": "rnbqk2r/pp2ppbp/6p1/2p5/3PP3/2P2N2/P4PPP/R1BQKB1R w KQkq - 0 8"
 },
 {
  "id": "o-benoni",
  "tier": 7,
  "title": "The Modern Benoni",
  "body": "Black accepts a space disadvantage and an asymmetric structure in return for the half-open e-file, queenside pawn majority and the powerful g7 bishop. It is sharp, unbalanced and a genuine winning attempt with Black — at the cost of real risk.",
  "points": [
   "Queenside pawn majority is the long-term asset",
   "...b5 is the freeing break; prepare it with ...a6 and ...Re8",
   "White's e4-e5 push is the danger to watch"
  ],
  "mode": "explore",
  "note": "Asymmetric pawns: Black owns the queenside majority, White owns the centre.",
  "fen": "rnbqk2r/pp3pbp/3p1np1/2pP4/4P3/2N2N2/PP3PPP/R1BQKB1R w KQkq - 2 8"
 },
 {
  "id": "o-benko",
  "tier": 7,
  "title": "The Benko Gambit",
  "body": "3...b5 offers a wing pawn for lasting pressure down the a- and b-files. The compensation is unusual because it is positional rather than tactical: even in the endgame Black's rooks keep pressing. It is one of the soundest gambits in chess.",
  "points": [
   "A pawn for permanent pressure on two open files",
   "The compensation survives into the endgame",
   "Bg7, Ra6-b6 and doubled rooks are the standard setup"
  ],
  "mode": "explore",
  "note": "Black is a pawn down with two open files and no risk. Unusual, and genuinely sound.",
  "fen": "rn1qkb1r/4pp1p/3p1np1/2pP4/4P3/2N5/PP3PPP/R1BQ1KNR w kq - 0 9"
 },
 {
  "id": "o-dutch",
  "tier": 7,
  "title": "The Dutch Defence",
  "body": "1...f5 fights for e4 and signals kingside ambitions immediately. The three main flavours are the Leningrad (...g6), the Classical (...e6 and ...Be7) and the Stonewall (...d5, ...e6, ...c6). The catch is that ...f5 slightly loosens the king — so watch out for early tricks.",
  "points": [
   "Fights for e4 and aims at the kingside",
   "Leningrad, Classical and Stonewall are the three systems",
   "Beware 2.e4 gambits and early Bg5/Qh5 tricks"
  ],
  "mode": "explore",
  "note": "The Stonewall. Pawns on c6, d5, e6, f5 grip e4 — and the dark squares are the price.",
  "fen": "rnbqk2r/pp4pp/2pbpn2/3p1p2/2PP4/5NP1/PP2PPBP/RNBQ1RK1 w kq - 0 7"
 },
 {
  "id": "o-budapest",
  "tier": 7,
  "title": "The Budapest Gambit",
  "body": "2...e5 offers a pawn immediately. After 3.dxe5 Ng4 Black regains it with ...Ngxe5 or ...Bc5 and quick development, and White must know a few precise moves or drift into trouble. A very effective surprise weapon at club level.",
  "points": [
   "The pawn comes back with ...Ng4 and ...Ngxe5",
   "Watch for the cheeky ...Bb4+ and ...Qe7 tricks",
   "Great surprise value, genuinely playable"
  ],
  "mode": "explore",
  "note": "Black is a pawn down but every piece is active and e5 is falling next move.",
  "fen": "r1bqk2r/pppp1ppp/2n5/4P3/1bP2Bn1/5N2/PP2PPPP/RN1QKB1R w KQkq - 5 6"
 },
 {
  "id": "o-catalan",
  "tier": 7,
  "title": "The Catalan",
  "body": "White combines d4 and c4 with a kingside fianchetto, so the g2 bishop presses down the long diagonal straight into Black's queenside. It is a slow, powerful squeeze — the bishop is sometimes still the best piece on the board forty moves later.",
  "points": [
   "The g2 bishop is the whole opening",
   "If Black takes on c4, White usually regains it with Qa4 or Ne5",
   "Patient pressure rather than a fast attack"
  ],
  "mode": "explore",
  "note": "Qc2 will pick up the c4 pawn while the g2 bishop keeps pressing. Slow and strong.",
  "fen": "rnbq1rk1/ppp1bppp/4pn2/8/2pP4/5NP1/PPQ1PPBP/RNB2RK1 b - - 1 7"
 },
 {
  "id": "o-albin",
  "tier": 7,
  "title": "The Albin Counter-Gambit",
  "body": "2...e5!? answers a gambit with a gambit. After 3.dxe5 d4 Black's advanced d-pawn is a genuine thorn, and there is a famous trap: 4.e3? Bb4+ 5.Bd2 dxe3! and if 6.Bxb4?? exf2+ 7.Ke2 fxg1=N+! wins. Sharp and rare.",
  "points": [
   "The d4 pawn cramps White for the whole game",
   "Famous trap ends with an underpromotion to a knight",
   "Risky but full of practical chances"
  ],
  "mode": "explore",
  "note": "If White grabs the bishop now, ...exf2+ and a knight underpromotion wins on the spot.",
  "fen": "rnbqk1nr/ppp2ppp/8/4P3/1bP5/4p3/PP1B1PPP/RN1QKBNR w KQkq - 0 6"
 },
 {
  "id": "o-english",
  "tier": 7,
  "title": "The English Opening",
  "body": "1.c4 grabs d5 from the side. It can transpose into almost anything — Queen's Gambit, Catalan, reversed Sicilian — which makes it both flexible and hard to prepare against. The Botvinnik setup with c4, Nc3, g3, Bg2, e4 and Nge2 is a great all-purpose plan.",
  "points": [
   "Fights for d5 without committing the d-pawn",
   "Often a Sicilian with colours reversed and a tempo",
   "Botvinnik setup: c4, Nc3, g3, Bg2, e4, Nge2"
  ],
  "mode": "explore",
  "note": "This is a Sicilian Dragon with colours reversed — and White has an extra tempo.",
  "fen": "r1bqk2r/ppp1bppp/1nn5/4p3/8/2N2NP1/PP1PPPBP/R1BQ1RK1 w kq - 6 8"
 },
 {
  "id": "o-reti",
  "tier": 7,
  "title": "The Réti Opening",
  "body": "1.Nf3 followed by c4 and g3 attacks the centre from the flanks without occupying it. The move order is a weapon in itself: White watches what Black commits to and then chooses the most awkward structure in reply. Flexible, modern and very hard to prepare for.",
  "points": [
   "Control the centre from a distance",
   "Transposes into English, Catalan or QGD at will",
   "Move-order flexibility is the real advantage"
  ],
  "mode": "explore",
  "note": "White has just transposed into a Catalan, having kept every option open until now.",
  "fen": "rnbq1rk1/ppp1bppp/4pn2/3p4/2PP4/5NP1/PP2PPBP/RNBQ1RK1 b - - 0 6"
 },
 {
  "id": "o-kia",
  "tier": 7,
  "title": "The King's Indian Attack",
  "body": "Nf3, g3, Bg2, O-O, d3, Nbd2 and e4 — a King's Indian Defence with an extra tempo, played as White against almost anything. Fischer used it with great success. One setup, one plan, and a standard kingside attack with e5, Nf1-g3 and h4.",
  "points": [
   "The same seven moves against nearly everything",
   "Standard plan: e4-e5, Nf1-g3, then h4 and the attack",
   "Minimum theory, maximum familiarity"
  ],
  "mode": "explore",
  "note": "The full KIA setup. Next comes e5, then the knight tour to g3 and a kingside attack.",
  "fen": "rnbq1rk1/pp2bppp/4pn2/2pp4/4P3/3P1NP1/PPPN1PBP/R1BQ1RK1 b - - 0 7"
 },
 {
  "id": "o-bird",
  "tier": 7,
  "title": "Bird's Opening and 1.b3",
  "body": "1.f4 is a Dutch Defence with an extra tempo, aiming at e5 and a kingside attack; 1.b3 (Larsen's Opening) fianchettoes immediately and pressures e5 from b2. Both are offbeat, both are sound, and both guarantee your opponent is on his own from move one.",
  "points": [
   "1.f4 grips e5; watch out for the From Gambit with 1...e5",
   "1.b3 is flexible, solid and almost theory-free",
   "Offbeat but perfectly sound"
  ],
  "mode": "explore",
  "note": "A double fianchetto Bird setup — nothing to memorise, and a clear kingside plan.",
  "fen": "rnbq1rk1/pp2ppbp/5np1/2pp4/5P2/1P2PN2/PBPPB1PP/RN1Q1RK1 b - - 1 7"
 },
 {
  "id": "o-blackrep",
  "tier": 7,
  "title": "Building a Black repertoire",
  "body": "You need exactly two answers as Black: one for 1.e4 and one for 1.d4. Pick systems whose ideas repeat rather than lines you must memorise. A tested, low-maintenance pair is the Caro-Kann or Scandinavian against 1.e4, and the Slav or King's Indian against 1.d4.",
  "points": [
   "Two openings is enough. Two. Not ten.",
   "Prefer systems with repeating ideas over forcing theory",
   "Change only when you understand why you are changing"
  ],
  "mode": "read"
 },
 {
  "id": "o-whiterep",
  "tier": 7,
  "title": "Building a White repertoire",
  "body": "Choose one first move and stick to it for at least a year. With 1.e4 you need answers to the Sicilian, French, Caro-Kann and 1...e5 — pick the low-theory option in each. With 1.d4 the London or Colle covers nearly everything with one setup. Depth beats breadth every time.",
  "points": [
   "One first move, held for a year at least",
   "1.e4: use the anti-Sicilians rather than the Open Sicilian at first",
   "1.d4: a system opening covers almost everything"
  ],
  "mode": "read"
 },
 {
  "id": "o-transpose",
  "tier": 7,
  "title": "Move orders and transpositions",
  "body": "The same position is often reachable by several routes, and strong players use this to steer opponents into what they know and away from what they do not. You do not need to master it — but you must recognise when a familiar position has arrived by an unfamiliar road.",
  "points": [
   "Judge the position in front of you, not the move order",
   "Move orders can dodge your opponent's preparation",
   "If it looks familiar, trust the plan, not the move number"
  ],
  "mode": "explore",
  "note": "This is a Queen's Gambit Declined, reached without ever playing 1.d4 or 2.c4 in that order.",
  "fen": "rnbqkb1r/ppp2ppp/4pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R b KQkq - 0 4"
 },
 {
  "id": "o-traps-summary",
  "tier": 7,
  "title": "The traps worth knowing",
  "body": "You do not need a trap collection, but a handful appear again and again below 1800. Know these six and you will both avoid and inflict a lot of short losses: Scholar's Mate, Fried Liver, Légal's Mate, the Petrov's Qe2 pin, Noah's Ark and the Elephant Trap.",
  "points": [
   "Traps are a bonus, not a strategy",
   "Know the six common ones from both sides",
   "If a trap fails, you must still have a decent position"
  ],
  "mode": "solve",
  "task": "Black to play. White just grabbed on d5. Punish it.",
  "accept": [
   "Nxd5"
  ],
  "hint": "The knight on d7 is not the only defender. What happens after the recapture?",
  "answer": "Nxd5! — the Elephant Trap. If Bxd8 then Bb4+ wins the queen back with interest.",
  "fen": "r1bqkb1r/pppn1ppp/5n2/3N2B1/3P4/8/PP2PPPP/R2QKBNR b KQkq - 0 6"
 }
]
);})();
