// Extra tiers shown after the app's original five.
// Generated by tools/build-content.js — edit the data in tools/, then rebuild.
(function(){var C=window.KS_CONTENT=window.KS_CONTENT||{tiers:[],lessons:[],puzzles:[]};
C.tiers=C.tiers.concat(
[
 {
  "id": 6,
  "name": "Opening Book: 1.e4",
  "band": "800–1800",
  "glyph": "♙",
  "tint": "var(--t6)",
  "intro": "Every major 1.e4 opening, with the plan behind it and the traps on the way."
 },
 {
  "id": 7,
  "name": "Opening Book: 1.d4",
  "band": "800–1800",
  "glyph": "♘",
  "tint": "var(--t7)",
  "intro": "Queen's pawn, Indian defences, flank openings, and how to build a repertoire."
 },
 {
  "id": 8,
  "name": "Opening Encyclopedia",
  "band": "Reference",
  "glyph": "♗",
  "tint": "var(--t8)",
  "intro": "Two hundred named openings with move order and the idea in one line. Look things up."
 },
 {
  "id": 9,
  "name": "Middlegame Mastery",
  "band": "1200–1800",
  "glyph": "♖",
  "tint": "var(--t9)",
  "intro": "Plans, structures, attack and defence — what to do once the pieces are out."
 },
 {
  "id": 10,
  "name": "Endgame Technique",
  "band": "1000–1800",
  "glyph": "♕",
  "tint": "var(--t10)",
  "intro": "The endings that decide club games, from the opposition to Lucena and Philidor."
 },
 {
  "id": 11,
  "name": "The 1800 Checklist",
  "band": "Habits",
  "glyph": "♔",
  "tint": "var(--t11)",
  "intro": "Clock, blunders, study method and review — the habits that actually move a rating."
 }
]
);})();
