// Builds content/*.js from the authored data in tools/.
// FENs are derived from move lists, puzzle answers are derived by search, and
// anything that does not check out fails the build.
//
//   node tools/build-content.js
const fs = require("fs");
const path = require("path");
const { Chess } = require("./node_modules/chess.js");
const { analyse } = require("./tactics-check.js");
const V = require("./verify.js");

const OUT = path.join(__dirname, "..", "content");
if (!fs.existsSync(OUT)) fs.mkdirSync(OUT);

const TIERS = [
  { id:6,  name:"Opening Book: 1.e4",  band:"800–1800", glyph:"♙", tint:"var(--t6)",
    intro:"Every major 1.e4 opening, with the plan behind it and the traps on the way." },
  { id:7,  name:"Opening Book: 1.d4",  band:"800–1800", glyph:"♘", tint:"var(--t7)",
    intro:"Queen's pawn, Indian defences, flank openings, and how to build a repertoire." },
  { id:8,  name:"Opening Encyclopedia", band:"Reference",    glyph:"♗", tint:"var(--t8)",
    intro:"Two hundred named openings with move order and the idea in one line. Look things up." },
  { id:9,  name:"Middlegame Mastery",  band:"1200–1800", glyph:"♖", tint:"var(--t9)",
    intro:"Plans, structures, attack and defence — what to do once the pieces are out." },
  { id:10, name:"Endgame Technique",   band:"1000–1800", glyph:"♕", tint:"var(--t10)",
    intro:"The endings that decide club games, from the opposition to Lucena and Philidor." },
  { id:11, name:"The 1800 Checklist",  band:"Habits",        glyph:"♔", tint:"var(--t11)",
    intro:"Clock, blunders, study method and review — the habits that actually move a rating." }
];

// 1.e4 c5 2.Nf3 ...
function numberMoves(moves) {
  let out = "";
  for (let i = 0; i < moves.length; i++) {
    if (i % 2 === 0) out += (i ? " " : "") + (i / 2 + 1) + "." + moves[i];
    else out += " " + moves[i];
  }
  return out;
}

function fenFromMoves(moves) {
  const c = new Chess();
  for (const m of moves) c.move(m);
  return c.fen();
}

// --- lessons ---------------------------------------------------------------
function buildLessons(mods) {
  const out = [];
  for (const L of [].concat(...mods)) {
    const les = Object.assign({}, L);
    if (les.moves) { les.fen = fenFromMoves(les.moves); delete les.moves; }
    delete les.expect;
    out.push(les);
  }
  return out;
}

// --- encyclopedia: groups of entries become one `read` lesson each ---------
function buildEncyclopedia(groups) {
  const out = [];
  for (const g of groups) {
    if (!g.entries) { out.push(g); continue; }
    const points = g.entries.map(e => {
      const c = new Chess();
      for (const m of e.moves) c.move(m);          // validated on the way past
      const eco = e.eco ? " (" + e.eco + ")" : "";
      return e.name + eco + " — " + numberMoves(e.moves) + " · " + e.idea;
    });
    out.push({ id: g.id, tier: g.tier, title: g.title, body: g.body, points, mode: "read" });
  }
  return out;
}

// --- puzzles: accept comes from the engine, never from hand -----------------
function buildPuzzles(puzzles) {
  const out = [];
  const problems = [];
  for (const p of puzzles) {
    const r = analyse(p);
    if (r.error) { problems.push(p.id + ": " + r.error); continue; }
    out.push({ id: p.id, theme: p.theme, level: p.level, fen: p.fen,
               task: p.task, accept: r.accept, answer: p.answer });
  }
  if (problems.length) {
    console.error("puzzle problems:\n  " + problems.join("\n  "));
    process.exit(1);
  }
  return out;
}

function write(file, key, data, note) {
  const header =
    "// " + note + "\n" +
    "// Generated by tools/build-content.js — edit the data in tools/, then rebuild.\n" +
    "(function(){var C=window.KS_CONTENT=window.KS_CONTENT||{tiers:[],lessons:[],puzzles:[]};\n" +
    "C." + key + "=C." + key + ".concat(\n";
  const body = JSON.stringify(data, null, 1);
  fs.writeFileSync(path.join(OUT, file), header + body + "\n);})();\n");
  return data.length;
}

const openings = buildLessons([
  require("./data-openings-e4.js"),
  require("./data-openings-d4.js")
]);
const encyclopedia = buildEncyclopedia([].concat(
  require("./data-encyclopedia-e4.js"),
  require("./data-encyclopedia-d4.js")
));
const middlegame = buildLessons([require("./data-middlegame.js")]);
const endgames  = buildLessons([require("./data-endgames.js")]);
const tips      = buildLessons([require("./data-tips.js")]);
const puzzles   = buildPuzzles(require("./data-puzzles.js"));

// every generated lesson goes through the verifier one last time
const all = [].concat(openings, encyclopedia, middlegame, endgames, tips);
all.forEach(V.verifyLesson);
const ids = {};
for (const l of all) { if (ids[l.id]) V.errors.push("duplicate lesson id " + l.id); ids[l.id] = 1; }
for (const t of TIERS) if (!all.some(l => l.tier === t.id)) V.errors.push("tier " + t.id + " has no lessons");
if (V.errors.length) {
  console.error("build failed:\n  " + V.errors.join("\n  "));
  process.exit(1);
}

let n = 0;
n += write("tiers.js",        "tiers",   TIERS,         "Extra tiers shown after the app's original five.");
n += write("openings.js",     "lessons", openings,      "Taught opening lessons (tiers 6 and 7).");
n += write("encyclopedia.js", "lessons", encyclopedia,  "Opening reference (tier 8).");
n += write("middlegame.js",   "lessons", middlegame,    "Middlegame lessons (tier 9).");
n += write("endgames.js",     "lessons", endgames,      "Endgame lessons (tier 10).");
n += write("tips.js",         "lessons", tips,          "Practical play and study habits (tier 11).");
n += write("puzzles.js",      "puzzles", puzzles,       "Extra tactics puzzles.");

const entries = encyclopedia.reduce((s, l) => s + (l.points ? l.points.length : 0), 0);
console.log("tiers        " + TIERS.length);
console.log("openings     " + openings.length + " lessons");
console.log("encyclopedia " + encyclopedia.length + " pages (" + entries + " openings)");
console.log("middlegame   " + middlegame.length + " lessons");
console.log("endgames     " + endgames.length + " lessons");
console.log("tips         " + tips.length + " lessons");
console.log("puzzles      " + puzzles.length);
console.log("\ntotal new lessons: " + all.length);
